"""Validates src/storm_reoptimizer/data/toy_india_topology.json, generated by
scripts/convert_tata_topology.py from the real TataNld.gml backbone. These
tests guard the data file itself, not the conversion script -- if the script
changes, re-run it and these tests should still hold for the output."""
import json
from pathlib import Path

TOPOLOGY_PATH = (
    Path(__file__).parent.parent
    / "src" / "storm_reoptimizer" / "data" / "toy_india_topology.json"
)

# Rough bounding box for India, generous enough to not be a real constraint --
# a sanity check that lat/lon weren't swapped or mis-parsed, not a precise border.
INDIA_LAT_RANGE = (6.0, 38.0)
INDIA_LON_RANGE = (68.0, 98.0)

KEY_CITIES = {"delhi", "mumbai", "kolkata", "chennai", "bangalore", "hyderabad", "nagpur"}


def _load():
    return json.loads(TOPOLOGY_PATH.read_text())


def test_topology_file_parses_with_expected_shape():
    data = _load()
    assert set(data.keys()) >= {"graph", "srlgs"}
    assert isinstance(data["srlgs"], list)
    for node in data["graph"]["nodes"]:
        assert set(node.keys()) == {"id", "lat", "lon"}
    for edge in data["graph"]["edges"]:
        assert set(edge.keys()) == {"src", "dst", "length_km", "mount_type"}
        assert edge["mount_type"] in {"aerial", "buried"}
        assert edge["length_km"] > 0


def test_node_count_and_key_cities_present():
    data = _load()
    node_ids = {n["id"] for n in data["graph"]["nodes"]}
    # 143 = 145 TataNld.gml nodes minus 2 "hyperedge" junction markers (no
    # real lat/lon, label "None") dropped by the conversion script.
    assert len(node_ids) == 143
    assert KEY_CITIES <= node_ids


def test_no_duplicate_edges_and_no_hyperedge_junction_leftovers():
    data = _load()
    edges = data["graph"]["edges"]
    pairs = [tuple(sorted((e["src"], e["dst"]))) for e in edges]
    assert len(pairs) == len(set(pairs)), "parallel (src,dst) duplicates should have been deduped"
    node_ids = {n["id"] for n in data["graph"]["nodes"]}
    for e in edges:
        assert e["src"] in node_ids and e["dst"] in node_ids
        assert not e["src"].startswith("node_") and not e["dst"].startswith("node_"), (
            "a 'node_<gml_id>' fallback slug means an unlabeled (hyperedge "
            "junction) node leaked into an edge instead of being dropped"
        )


def test_node_coordinates_are_within_india():
    data = _load()
    for n in data["graph"]["nodes"]:
        assert INDIA_LAT_RANGE[0] <= n["lat"] <= INDIA_LAT_RANGE[1], n
        assert INDIA_LON_RANGE[0] <= n["lon"] <= INDIA_LON_RANGE[1], n


def test_mount_type_split_is_not_degenerate():
    # Guards against reintroducing the near-degenerate 165/16 (or worse 178/3)
    # split found during conversion -- the storm scenario needs a real mix of
    # exposed (aerial) and safe (buried) spans to be a meaningful demo.
    data = _load()
    edges = data["graph"]["edges"]
    aerial = sum(1 for e in edges if e["mount_type"] == "aerial")
    buried = len(edges) - aerial
    assert aerial > len(edges) * 0.2
    assert buried > len(edges) * 0.2


def test_delhi_nagpur_disjoint_route_edges_present_with_expected_mount_types():
    # The specific route pair Task 4's round-trip test relies on, discovered
    # via the server's own compute_disjoint_paths (not hand-picked). Recorded
    # here so a topology regeneration that silently changes these edges'
    # mount_type or removes a node fails loudly instead of breaking Task 4
    # with a confusing assertion deep in an MCP round-trip.
    data = _load()
    by_pair = {tuple(sorted((e["src"], e["dst"]))): e for e in data["graph"]["edges"]}

    def mount_type(a, b):
        return by_pair[tuple(sorted((a, b)))]["mount_type"]

    working_edges = [
        ("delhi", "mathura"), ("mathura", "agra"), ("agra", "gwalior"),
        ("gwalior", "jhansi"), ("jhansi", "satna"), ("satna", "jabalpur"),
        ("jabalpur", "raipur"), ("raipur", "bhandara"), ("bhandara", "nagpur"),
    ]
    protection_edges = [
        ("delhi", "jaipur"), ("jaipur", "bhilwara"), ("bhilwara", "ratlam"),
        ("ratlam", "ujjain"), ("ujjain", "dhar"), ("dhar", "khandwa"),
        ("khandwa", "jalgaon"), ("jalgaon", "buldhana"), ("buldhana", "amravati"),
        ("amravati", "nagpur"),
    ]
    for a, b in working_edges + protection_edges:
        assert (a, b) in by_pair or (b, a) in by_pair, f"missing edge {a}-{b}"

    # The storm's exposed pair: one aerial span on each route, in the same
    # central-India latitude band (~20-25N) -- a plausible single footprint.
    assert mount_type("jhansi", "satna") == "aerial"
    assert mount_type("ratlam", "ujjain") == "aerial"
    # And working/protection are otherwise NOT both aerial at every hop --
    # this is the "SRLG-disjoint at design time" case, not "everything's exposed".
    assert mount_type("agra", "gwalior") == "buried"
    assert mount_type("jaipur", "bhilwara") == "buried"
